[package]
name = "evolutionator"
authors = ["jordan@butterwick.tech"]
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version="0.9", features = ["dynamic"] }
rand = "0.8.5"
alsa = "=0.7.0"